
name = "Esophagus"
lighting = true
particle_render_factor = 1.0
kernel_radius = 0.010
view_angle = 90.0
view_scale = 1.5
# view_pos = [0.0,-0.3]
gravity = 5.0
time_step = 0.0001
artificial_viscocity = 0.0
subticks = 1
integrator = "RK4"
# subticks = 1
# integrator = "Verlet"

min = [-0.2,-0.4,-0.4]
dim = [0.4,2.0,0.8]

[objects.stomach]
  packing = 0.5
  density = 1.0
  normal_stiffness = -3000000.0
  shear_stiffness = -300000000.0
  shear_dampening = -5000.0
  color = [0.0,1.0,0.0,0.1]
  union = [
    {border=0.07, scale = [0.04,0.04,0.04], model = "examples/models/stomach surface.stl"},
    {center = [-0.0,-0.22,0.17], dim = [0.07,0.07,0.02]},
    {difference = [{center = [-0.0,0.32,-0.16], dim = [0.055,0.06,0.11]}, {center = [-0.0,0.305,-0.16], radii = [0.012,0.5,0.012]}]}
  ]

[objects.fluid]
  packing = 0.5
  speed_of_sound = 3000.0
  viscocity = 0.0
  bulk_viscocity = 5000.0
  color = [0.0,0.0,1.0,0.1]
  density = 1.0
  stomach = {contact_factor = 0.25, friction = 0.0, dampening = 0.0}
  region = {center = [-0.0,0.52,-0.16], dim = [0.05,0.32,0.10]}

[boundaries.side_pin]
stomach = {friction = 1.0}
color = [0.0,0.0,0.0,0.0]
union = [
  {center = [0.0,0.04,0.12], radii = [0.015,0.015,0.015]},
  {center = [0.0,0.05,0.09], radii = [0.01,0.01,0.01]},
  {center = [0.0,0.05,0.05], radii = [0.01,0.01,0.01]},
  {center = [-0.075,0.0,0.07], dim = [0.01,0.2,0.2]},
  {center = [0.075,0.0,0.07], dim = [0.01,0.2,0.2]},
]

[boundaries.esophagus_pin]
  stomach = {friction = 1.0}
  color = [0.0,0.0,0.0,1.0]
  difference = [
    {center = [-0.0,0.485,-0.16], dim = [0.08,0.43,0.13]},
    {center = [-0.0,0.485,-0.16], dim = [0.07,0.41,0.12]},
    {center = [-0.0,0.275,-0.15], radii = [0.027,0.5,0.027]}
  ]

[boundaries.duodenum_pin]
  stomach = {friction = 1.0}
  color = [0.0,0.0,0.0,0.0]
  difference = [
    {center = [-0.0,-0.22,0.15], dim = [0.15,0.12,0.007]},
    {center = [-0.0,-0.22,0.15], radii = [0.025,0.025,0.5]}
  ]

[boundaries.support]
  stomach = {friction = 1.0}
  color = [0.0,0.0,0.0,0.0]
  union = [
    {center = [-0.0,-0.19,0.08], dim = [0.15,0.01,0.01]},
    {center = [-0.0,-0.185,0.1], dim = [0.15,0.01,0.01]},
    {center = [-0.0,-0.18,0.12], dim = [0.15,0.01,0.01]}
  ]

[boundaries.exit_pin]
  stomach = {friction = 1.0}
  color = [0.0,0.0,0.0,0.0]
  difference = [
    {center = [-0.0,-0.21,-0.035], dim = [0.15,0.02,0.23]},
    {center = [-0.0,-0.21,-0.035], radii = [0.04,0.5,0.04]}
  ]

[boundaries.entrance_pin]
  stomach = {friction = 1.0}
  color = [0.0,0.0,0.0,0.0]
  difference = [
    {center = [-0.0,0.03,-0.0], dim = [0.15,0.12,0.007]},
    {center = [-0.0,0.03,-0.0], radii = [0.04,0.04,0.5]}
  ]
