
name = "Gas Test"
kernel_radius = 0.008
gravity = 3.1
time_step = 0.0001
subticks = 1
artificial_viscocity = 5.0
integrator = "RK4"

min = [-0.2,-1.0]
dim = [0.4,1.0]

[liquids.circle]
  speed_of_sound = 1000.0
  density = 20.0
  color = [0.0,0.0,1.0,1.0]
  region = {center = [-0.0,-0.2], radii = [0.03,0.05]}

[gasses.gas]
  speed_of_sound = 1000.0
  start_density = 0.1
  target_density = 0.0
  viscocity = 0.0
  color = [0.0,0.0,0.0,0.125]
  color_low_density = [0.0,0.0,0.0,0.0]
  color_high_density = [1.0,0.0,0.0,0.25]

  difference = [
    {min = [-0.17,-0.97], dim = [0.34,0.94]},
    {center = [-0.0,-0.2], radii = [0.037,0.057]}
  ]


[boundaries.border]
  friction = 0.0
  region = {min = [-0.2,-1.0], dim = [0.4,1.0], border = 0.02}


# [liquids.circle]
#   friction = 0.0
#   region = {center = [-0.0,-0.7], radii = [0.02,0.02]}
