
name = "Ink Drop in 2D"
kernel_radius = 0.008
gravity = 4.1
time_step = 0.01
subticks = 21
artificial_viscocity = 25.0
integrator = "RK4"

min = [-0.3,-1.0]
dim = [0.6,1.5]

[liquids.f1]
  speed_of_sound = 6000.0
  viscocity = 0.0
  color = [0.0,0.0,1.0,1.0]
  color_low_density = [0.0,1.0,0.0,1.0]
  color_high_density = [1.0,0.0,0.0,1.0]
  region = {min = [-0.27,-0.97], dim = [0.54,0.3]}


[liquids.f2]
  viscocity = 0.0
  speed_of_sound = 6000.0
  color = [0.0,0.0,0.0,1.0]
  density = 1.1
  region = {center = [0.0, 0.175], radii = [0.02,0.02]}


[boundaries.border]
  friction = 0.0
  region = {min = [-0.3,-1.0], dim = [0.6,1.5], border = 0.02}
