
name = "Model Import Test"
lighting = true
particle_render_factor = 0.7
kernel_radius = 0.02
gravity = 5.0
time_step = 0.001
subticks = 6
artificial_viscocity = 0.0
integrator = "RK4"

min = [-0.5,-0.6,-0.5]
dim = [1.0,1.0,1.0]

[objects.gear]
  packing = 0.7
  density = 1.0
  normal_stiffness = -3000000.0
  shear_stiffness = -300000000.0
  shear_dampening = -5000.0
  color = [0.0,0.0,1.0,1.0]
  # color_high_density = [1.0,0.0,0.0,0.1]
  # color_low_density = [0.0,1.0,0.0,0.1]
  # region = {translation = [0.0,0.1,0.0], scale = [1.0,1.0,1.0], model = "examples/models/gear2.stl"}
  region = {translation = [0.0,0.1,0.0], scale = [0.03,0.03,0.03], model = "examples/models/gear3.stl"}
  # region = {translation = [0.0,0.1,-0.2], scale = [0.2,0.2,0.2], model = "examples/models/shaft2_wheels4.STL"}
  # region = {translation = [0.0,0.1,0.0], scale = [0.04,0.04,0.04], model = "examples/models/non_hollow_stomach.stl"}

# [objects.gear.region]
#   scale = [0.025,0.025,0.025]
#   union = [{translation = [1207.713, 7187.29, 1527.9222, 0.0], model = "examples/models/esophagus_stomach_duodenum.stl"}]


[boundaries.floor]
  packing = 0.5
  friction = 1.0
  color = [0.0,0.0,0.0,0.01]
  region = {min = [-0.5,-0.3,-0.5], dim = [1.0,0.06,1.0]}

# [boundaries.circle]
#   packing = 0.5
#   friction = 1.0
#   color = [0.0,0.0,0.0,0.05]
#   region = {center = [0.05,-0.35,-0.2], diameters = [0.06,0.06,0.06]}
