
name = "Model Import Test"
lighting = true
particle_render_factor = 0.7
kernel_radius = 0.02
gravity = 5.0
time_step = 0.001
subticks = 4
artificial_viscocity = 0.0
integrator = "Verlet"

min = [-0.5,-0.6,-0.5]
dim = [1.0,1.0,1.0]

[objects.gear]
  packing = 0.7
  density = 1.0
  normal_stiffness = -300000.0
  shear_stiffness = -30000000.0
  shear_dampening = -10000.0
  color = [0.0,0.0,1.0,1.0]
  # color_high_density = [1.0,0.0,0.0,0.1]
  # color_low_density = [0.0,1.0,0.0,0.1]
  region = {model = "examples/models/gear.stl"}


[boundaries.floor]
  packing = 0.5
  friction = 1.0
  color = [0.0,0.0,0.0,0.01]
  region = {min = [-0.5,-0.3,-0.5], dim = [1.0,0.06,1.0]}

# [boundaries.circle]
#   packing = 0.5
#   friction = 1.0
#   color = [0.0,0.0,0.0,0.05]
#   region = {center = [0.05,-0.35,-0.2], diameters = [0.06,0.06,0.06]}
