
name = "Raindrop"
preferred_tickrate = 1
lighting = false
particle_render_factor = 1.0
view_scale = 1.5
view_pos = [0.0,0.5,0.0]
kernel_radius = 0.005
gravity = 3.1
time_step = 0.0001
subticks = 10
integrator = "RK4"

min = [-0.2,-1.0]
dim = [0.4,1.0]

[objects.circle]
  packing = 0.5
  speed_of_sound = 1000.0
  bulk_viscocity = 100.0
  density = 20.0
  color = [0.0,0.0,1.0,1.0]
  region = {center = [-0.0,-0.2], radii = [0.03,0.03]}

  gas = {contact_strength = 20000.0}
  border = {contact_strength = 20000.0}

[objects.gas]
  packing = 0.5
  state_eq = "Ideal_Gas"
  speed_of_sound = 1000.0
  start_density = 0.05
  target_density = 0.00

  viscocity = 0.0
  bulk_viscocity = 100.0

  color = [0.2,0.2,0.2,0.0]
  color_low_density = [0.0,0.0,1.0,10.0]
  color_high_density = [1.0,0.0,0.0,10.0]

  difference = [
    {min = [-0.17,-0.97], dim = [0.34,0.94]},
    {center = [-0.0,-0.2], radii = [0.037,0.037]}
  ]

  border = {contact_strength = 20000.0}


[boundaries.border]
  friction = 0.0
  region = {min = [-0.2,-1.0], dim = [0.4,1.0], border = 0.02}


# [objects.circle]
#   friction = 0.0
#   region = {center = [-0.0,-0.7], radii = [0.02,0.02]}
