
name = "Rayleigh-Taylor Instability"
kernel_radius = 0.008
gravity = 5.1
time_step = 0.01
subticks = 31
artificial_viscocity = 0.0
integrator = "RK4"

min = [-0.2,-1.0,-0.2]
dim = [0.4,1.5,0.4]

[objects.f1]
  density = 1.0
  speed_of_sound = 6000.0
  viscocity = 1.0
  color = [0.0,0.0,1.0,1.0]
  color_low_density = [0.0,1.0,0.0,1.0]
  color_high_density = [1.0,0.0,0.0,1.0]
  region = {min = [-0.17,-0.47,-0.17], dim = [0.34,0.15,0.34]}

[objects.f2]
  density = 2.0
  speed_of_sound = 6000.0
  viscocity = 1.0
  color = [1.0,0.0,0.0,1.0]
  # color_low_density = [0.0,1.0,0.0,1.0]
  # color_high_density = [1.0,0.0,0.0,1.0]
  region = {min = [-0.17,-0.31,-0.17], dim = [0.34,0.15,0.34]}


[boundaries.border]
  friction = 0.0
  color = [0.0,0.0,0.0,0.0]
  region = {min = [-0.2,-0.5,-0.2], dim = [0.4,1.0,0.4], border = 0.02}
