
name = "Siphon Demo"
kernel_radius = 0.008
gravity = 25.1
time_step = 0.01
subticks = 60
artificial_viscocity = 0.0
integrator = "RK4"

min = [-0.4,-1.0]
dim = [1.6,1.1]

[objects.f1]
  speed_of_sound = 12000.0
  packing = 0.5
  viscocity = 8.0
  density = 1.0
  color = [0.0,0.0,1.0,1.0]
  color_low_density = [0.0,1.0,0.0,1.0]
  color_high_density = [1.0,0.0,0.0,1.0]

  region = {center = [0.3,-0.73], dim = [0.06,0.12]}

[objects.on_click]
  on_click = "Relative"
  packing = 0.5
  speed_of_sound = 12000.0
  viscocity = 8.0
  density = 1.0
  color = [0.0,0.0,1.0,1.0]
  color_low_density = [0.0,1.0,0.0,1.0]
  color_high_density = [1.0,0.0,0.0,1.0]

  region = {center = [0.0,0.0], dim = [0.08,0.12]}


[boundaries.border]
  friction = 0.0
  packing = 0.3
  difference = [
    {min = [-0.4,-1.0], dim = [1.6,1.1]},
    {min = [-0.25,-0.8], dim = [0.125,0.8]},
    {min = [-0.25,-0.8], dim = [0.20,0.04]},
    {min = [-0.075,-0.8], dim = [0.04,0.2]},
    {min = [-0.075,-0.6], dim = [0.16,0.03]},
    {min = [0.045,-0.95], dim = [0.03,0.35]},
    {min = [0.045,-0.95], dim = [0.3,0.015]},
    {min = [0.25,-0.95], dim = [0.7,1.0]}
  ]
