
name = "Elastic Ball"
lighting = true
particle_render_factor = 0.7
kernel_radius = 0.02
gravity = 5.0
time_step = 0.00016
subticks = 1
artificial_viscocity = 0.0
integrator = "Verlet"

min = [-0.3,-0.6,-0.5]
dim = [1.0,1.0,1.0]

[objects.ball]
  packing = 0.7
  density = 1.0
  strain_order = 0
  normal_stiffness = -80000000.0
  shear_stiffness = -20000000.0
  shear_dampening = -70000.0
  color = [0.0,0.0,1.0,1.0]
  # color_high_density = [1.0,0.0,0.0,0.1]
  # color_low_density = [0.0,1.0,0.0,0.1]
  region = {center = [-0.0,-0.2,-0.3], dim = [0.07,0.07,0.07]}
  floor = { potential = "linear", contact_strength = 10000.0 , friction = 0.5, contact_factor = 0.5}


[boundaries.floor]
  packing = 0.5
  color = [0.0,0.0,0.0,0.01]
  region = {min = [-0.2,-0.6,-0.5], dim = [0.4,0.06,0.4]}

# [boundaries.circle]
#   packing = 0.5
#   friction = 1.0
#   color = [0.0,0.0,0.0,0.05]
#   region = {center = [0.05,-0.35,-0.2], diameters = [0.06,0.06,0.06]}
