
name = "Elastic Ball"
kernel_radius = 0.01
gravity = 5.0
time_step = 0.001
subticks = 10
artificial_viscocity = 0.0
integrator = "RK4"

min = [-0.2,-1.0]
dim = [0.4,1.0]

[elastics.ball]
  packing = 0.7
  density = 1.0
  normal_stiffness = -400000.0
  shear_stiffness = -1000000.0
  # normal_dampening = -5000.0
  shear_dampening = -1000.0
  color = [0.0,0.0,1.0,1.0]
  color_high_density = [1.0,0.0,0.0,1.0]
  color_low_density = [0.0,1.0,0.0,1.0]
  region = {center = [-0.0,-0.75], dim = [0.08,0.08]}


[boundaries.floor]
  packing = 0.5
  friction = 0.0
  region = {min = [-0.2,-1.0], dim = [0.4,0.06]}

# [boundaries.circle]
#   packing = 0.5
#   friction = 0.0
#   region = {center = [0.03,-0.85], diameters = [0.03,0.03]}
