
name = "Wave in 3D"
kernel_radius = 0.02
particle_render_factor = 0.6
lighting = true
gravity = 2.1
time_step = 0.01
subticks = 2
artificial_viscocity = 200.0
integrator = "RK4"

min = [-1.0,-1.0,-1.0]
dim = [2.0,2.0,2.0]

[boundaries.border]
  friction = 0.0
  color = [0.0,0.0,0.0,0.0]
  packing = 0.5
  difference = [
    {min = [-0.5,-0.6,-0.12], dim = [1.0,1.0,0.24], border = 0.04},
    {min = [-0.6,0.3,-0.2], dim = [1.2,1.0,0.4]}
  ]

[objects.f1]
  packing = 0.5
  speed_of_sound = 3000.0
  viscocity = 0.0
  color = [0.0,0.0,1.0,0.1]
  density = 1.0
  #color_low_density = [0.0,1.0,0.0,0.1]
  #color_high_density = [1.0,0.0,0.0,0.1]

  union = [
    {center = [-0.4,-0.15, -0.0], dim = [0.08, 0.6, 0.115]},
    {center = [0.0,-0.485, -0.0], dim = [0.885,0.12, 0.115]}
  ]
